---
version: '3'

includes:
  common:
    taskfile: ./taskfiles/Taskfile.common.yaml
  pc:
    taskfile: ./taskfiles/Taskfile.precommit.yaml

tasks:
  default:
    desc: Default task
    cmds:
      - task: common:default
