---
version: '3'

includes:
    common: ./taskfiles/Taskfile.common.yaml
    go: ./taskfiles/Taskfile.golang.yaml
    pc: ./taskfiles/Taskfile.precommit.yaml
    tf: ./taskfiles/Taskfile.terraform.yaml

tasks:
    default:
        desc: Default task
        cmds:
            - task: common:default
