name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: bridgecrewio/checkov-action@v12.1347.0

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: terraform-linters/setup-tflint@v2.0.1
      - run: tflint --version
      - run: tflint --init
      - run: tflint -f compact

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: aquasecurity/tfsec-action@v1.0.2

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: terraform-docs/gh-actions@v1.0.0
      with:
        git-push: true
