---
name: Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bridgecrewio/checkov-action@v12

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v3.0.0
      - run: tflint --version
      - run: tflint --init
      - run: tflint -f compact

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-action@v1.0.2

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-push: true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-yamllint@v1.6.1
        with:
          level: error
