---
name: Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init --upgrade --backend=false
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: "--no-verify"

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v3.0.0
      - run: tflint --version
      - run: tflint --init
      - run: tflint -f compact

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ github.token }}

  docs:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-push: true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
