name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.2.0
      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: >-
            terraform_checkov

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: bridgecrewio/checkov-action@v12.1347.0
