---
name: Test

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: [main]

permissions:
    contents: write

jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup
              uses: hashicorp/setup-terraform@v3
            - name: Init
              run: terraform init --upgrade --backend=false
            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  commit_options: --no-verify

    test:
        runs-on: ubuntu-latest
        needs: init
        steps:
            - uses: actions/checkout@v5
            - uses: hashicorp/setup-terraform@v3
            - uses: actions/setup-go@v6
              with:
                  go-version-file: tests/go.mod
                  cache-dependency-path: tests/go.sum
            - name: Test
              working-directory: tests
              run: go test

    tflint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: terraform-linters/setup-tflint@v6
            - run: tflint --version
            - run: tflint --init
              env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
                  GITHUB_TOKEN: ${{ github.token }}
            - run: tflint -f compact

    tfsec:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: aquasecurity/tfsec-action@v1.0.3
              with:
                  github_token: ${{ github.token }}

    docs:
        runs-on: ubuntu-latest
        needs: init
        steps:
            - uses: actions/checkout@v5
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            - uses: terraform-docs/gh-actions@v1.4.1
              with:
                  git-push: true

    jsonlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Run JSON Lint
        # yamllint disable-line rule:line-length
              run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

    yamllint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: yaml-lint
              uses: ibiqlik/action-yamllint@v3
